### ISSUE TITLE
crashes on git files: Update required

### ISSUE THREAD

**Issue by imxade** [flathub/com.helix_editor.Helix#14]
issue: 
flatpak version of helix breaks while editing files tracked by git.

commit that got it fixed:
https://github.com/helix-editor/helix/pull/7227

**Comment by blt-r** [comment]
That PR isn't part of any new release, so there's nothing I can do about this. We'll just need to wait for upstream to release a new version with the bug fixed

**Comment by imxade** [comment]
New release : [23.10](https://github.com/helix-editor/helix/releases)

**Comment by blt-r** [comment]
Yeah I already updated the flatpak (#15), it should be on flathub soon. Meanwhile, if you want to see if the issue is fixed on new version, you can `flatpak install --user https://dl.flathub.org/build-repo/59300/com.helix_editor.Helix.flatpakref`

**Comment by blt-r** [comment]
Okay, it's on flathub now. You can update it and test to see if the issue is gone. If so, I'll close this

**Comment by imxade** [comment]
Fixed, thanks
