### ISSUE TITLE
pylsp

### ISSUE THREAD

**Issue by imxade** [flathub/com.helix_editor.Helix#16]
Please, bundle pylsp.
as according to [this](https://discourse.flathub.org/t/python-sdk-extension/2674) sdk extension won't be a viable option.

**Comment by blt-r** [comment]
I think freedesktop sdk includes pip, so you might be able to install pylsp as a pip package inside the sandbox. I'll look into this when I'm at home

**Comment by blt-r** [comment]
Also it seems the `ide-flatpak-wrapper` does something for python packages to work, and adds something to `$PATH`, so it'll probably work

**Comment by imxade** [comment]
> I think freedesktop sdk includes pip, so you might be able to install pylsp as a pip package inside the sandbox. I'll look into this when I'm at home

yes it does, my bad.
Installed pylsp
But it doesn't automatically get added to path, its located in ~/.local/bin

**Comment by blt-r** [comment]
Look into https://github.com/flathub/ide-flatpak-wrapper. I think `$FLATPAK_ISOLATE_PIP`, might be what we need here

**Comment by blt-r** [comment]
Actually, it's set by default, maybe it didn't work for you because you entered the sandbox with `--command=sh`, and the wrapper didn't get sourced

**Comment by imxade** [comment]
> Actually, it's set by default, maybe it didn't work for you because you entered the sandbox with `--command=sh`, and the wrapper didn't get sourced

yes, that's how I did it. Just bash instead of sh

**Comment by imxade** [comment]
currently using ``--env``

thanks for the help
