### ISSUE TITLE
Helix should be marked as "Console Application"

### ISSUE THREAD

**Issue by yannicka** [flathub/com.helix_editor.Helix#20]
There is an "App Type" filter with the value "Console Application", however Helix does not show up with this filter (it is found in "Desktop Application") even though it is a console application.

**Comment by blt-r** [comment]
"Console Application" is meant for CLI tools.  TUI apps are considered to be "Desktop Applications". This is part of the appstream spec. Other TUI text editors on flathub (neovim, vim, micro) are also under "Desktop Application" category
